/**
 * Hardened Sample Configuration
 * Best practices applied everywhere. Expected score: A (~92-98)
 *
 * - SSH: key-only, no root password, non-default port, low MaxAuthTries
 * - All users have 2FA
 * - Firewall: enabled, DROP default, explicit rules
 * - All containers unprivileged, no nesting
 * - API tokens: scoped, privilege-separated, with expiry
 * - Storage: root_squash, proper CIFS permissions
 */
import type { ConfigFileType } from '../types';

export const hardenedSample: Record<ConfigFileType, string> = {
  'sshd_config': `# Proxmox VE 8.2 SSH Configuration
# /etc/ssh/sshd_config
# Hardened configuration — CIS benchmark compliant

Port 2222
ListenAddress 192.0.2.1

# Strict authentication
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
MaxAuthTries 3
LoginGraceTime 30

# Disable unnecessary features
X11Forwarding no
AllowTcpForwarding no
PermitTunnel no
UsePAM yes

# Logging
LogLevel VERBOSE

# Allow only specific users
AllowGroups pvessh-admins

# Session limits
ClientAliveInterval 300
ClientAliveCountMax 2
MaxSessions 3

Subsystem sftp /usr/lib/openssh/sftp-server
`,

  'user.cfg': `# Proxmox VE User Configuration
# /etc/pve/user.cfg
# Hardened — all users with 2FA, minimal permissions

user:root@pam:1:0::::Superuser::
user:admin@pve:1:0:Sarah:Chen:sarah@example.com:Primary administrator::
user:operator@pve:1:0:Mike:Rodriguez:mike@example.com:Operations lead::
user:devops@pve:1:0:Alex:Kim:alex@example.com:DevOps engineer::
user:monitor@pve:1:0:Monitor:Service:monitor@example.com:Monitoring service::
user:readonly@pve:1:0:Audit:Compliance:audit@example.com:Security audit access::

group:admins:admin@pve:Cluster administrators:
group:operators:operator@pve,devops@pve:Operations team:
group:viewers:monitor@pve,readonly@pve:Read-only access:

role:VMOperator:VM.Audit,VM.Backup,VM.Console,VM.Monitor,VM.PowerMgmt,VM.Snapshot:
role:StorageUser:Datastore.Audit,Datastore.AllocateSpace:

acl:1:/:root@pam:Administrator:
acl:1:/vms:admin@pve:PVEVMAdmin:
acl:1:/storage:admin@pve:PVEDatastoreAdmin:
acl:1:/vms:operator@pve:VMOperator:
acl:1:/vms:devops@pve:VMOperator:
acl:1:/:monitor@pve:PVEAuditor:
acl:1:/:readonly@pve:PVEAuditor:

token:monitor@pve:grafana:1739404800:1:Grafana monitoring — expires 2025-02-13:
token:devops@pve:ansible:1742083200:1:Ansible automation — expires 2025-03-16:

tfa:root@pam:totp:
tfa:admin@pve:webauthn:
tfa:operator@pve:totp:
tfa:devops@pve:totp:
tfa:monitor@pve:totp:
tfa:readonly@pve:totp:
`,

  'cluster.fw': `# Proxmox VE Cluster Firewall Configuration
# /etc/pve/firewall/cluster.fw
# Hardened — DROP by default, explicit allow rules only

[OPTIONS]

enable: 1
policy_in: DROP
policy_out: ACCEPT
log_level_in: info
log_level_out: nolog
nf_conntrack_allow_invalid: 0

[RULES]

# Management access from trusted network only
IN ACCEPT -source 192.0.2.0/24 -p tcp -dport 8006 # Proxmox Web UI
IN ACCEPT -source 192.0.2.0/24 -p tcp -dport 2222 # SSH (custom port)
IN ACCEPT -source 192.0.2.0/24 -p tcp -dport 3128 # SPICE proxy
IN ACCEPT -source 192.0.2.0/24 -p tcp -dport 5900:5999 # VNC console range

# Cluster communication (corosync)
IN ACCEPT -source 198.51.100.0/24 -p udp -dport 5404:5405 # Corosync
IN ACCEPT -source 198.51.100.0/24 -p tcp -dport 60000:60050 # Live migration

# Monitoring
IN ACCEPT -source 203.0.113.5 -p tcp -dport 9100 # Node exporter
IN ACCEPT -source 203.0.113.5 -p tcp -dport 9090 # Prometheus

# ICMP for diagnostics
IN ACCEPT -p icmp

[IPSET management]

192.0.2.0/24
192.0.2.1

[IPSET cluster-nodes]

198.51.100.1
198.51.100.2
198.51.100.3
`,

  'iptables': `# Generated by iptables-save on Proxmox VE 8.2
# Hardened iptables with Proxmox firewall
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -s 192.0.2.0/24 -p tcp --dport 8006 -j ACCEPT
-A INPUT -s 192.0.2.0/24 -p tcp --dport 2222 -j ACCEPT
-A INPUT -s 192.0.2.0/24 -p tcp --dport 3128 -j ACCEPT
-A INPUT -s 198.51.100.0/24 -p udp --dport 5404:5405 -j ACCEPT
-A INPUT -s 198.51.100.0/24 -p tcp --dport 60000:60050 -j ACCEPT
-A INPUT -s 203.0.113.5/32 -p tcp --dport 9100 -j ACCEPT
-A INPUT -p icmp --icmp-type echo-request -j ACCEPT
-A INPUT -j LOG --log-prefix "[PVE-FW DROP] "
-A INPUT -j DROP
COMMIT
`,

  'lxc.conf': `# Container 300
hostname: web-proxy
unprivileged: 1
features: nesting=0
rootfs: local-lvm:vm-300-disk-0,size=8G
cores: 2
memory: 1024
swap: 0
net0: name=eth0,bridge=vmbr1,ip=192.0.2.30/24,gw=192.0.2.1

# Container 301
hostname: app-server
unprivileged: 1
features: nesting=0
rootfs: local-lvm:vm-301-disk-0,size=16G
cores: 4
memory: 4096
swap: 0
net0: name=eth0,bridge=vmbr1,ip=192.0.2.31/24,gw=192.0.2.1

# Container 302
hostname: db-replica
unprivileged: 1
features: nesting=0
rootfs: local-lvm:vm-302-disk-0,size=32G
cores: 4
memory: 8192
swap: 0
net0: name=eth0,bridge=vmbr2,ip=198.51.100.32/24,gw=198.51.100.1

# Container 303
hostname: log-collector
unprivileged: 1
features: nesting=0
rootfs: local-lvm:vm-303-disk-0,size=50G
cores: 2
memory: 2048
swap: 0
net0: name=eth0,bridge=vmbr2,ip=198.51.100.33/24,gw=198.51.100.1
`,

  'storage.cfg': `dir: local
	path /var/lib/vz
	content iso,vztmpl,backup
	maxfiles 7

lvmthin: local-lvm
	thinpool data
	vgname pve
	content rootdir,images

nfs: nas-backups
	server 198.51.100.10
	export /volume1/pve-backups
	content backup
	options vers=4.2,sec=krb5p
	maxfiles 14

nfs: nas-iso
	server 198.51.100.10
	export /volume1/iso-library
	content iso,vztmpl
	options vers=4.2,sec=krb5p,ro
`,
};
