/**
 * Insecure Sample Configuration
 * Everything is misconfigured. Expected score: F (~20-30)
 *
 * - Root SSH + password auth on port 22
 * - No 2FA for any user
 * - Firewall disabled
 * - Privileged containers with nesting
 * - Admin API tokens with no expiry
 * - NFS with no_root_squash
 */
import type { ConfigFileType } from '../types';

export const insecureSample: Record<ConfigFileType, string> = {
  'sshd_config': `# Proxmox VE 8.1 Default SSH Configuration
# /etc/ssh/sshd_config
# WARNING: This is an insecure default configuration

Port 22
#AddressFamily any
ListenAddress 0.0.0.0

# Authentication
PermitRootLogin yes
PasswordAuthentication yes
PubkeyAuthentication yes
PermitEmptyPasswords no
MaxAuthTries 10
LoginGraceTime 120

# Dangerous settings
X11Forwarding yes
UsePAM yes

# Subsystem
Subsystem sftp /usr/lib/openssh/sftp-server
`,

  'user.cfg': `# Proxmox VE User Configuration
# /etc/pve/user.cfg
# Generated: 2025-12-15T10:30:00Z

user:root@pam:1:0::::root account::
user:admin@pve:1:0:John:Doe:admin@example.com:Primary admin::
user:operator@pve:1:0:Jane:Smith:jane@example.com:Operations::
user:backup@pve:1:0:Backup:Service:backup@example.com:Backup service account::
user:dev@pve:1:0:Developer:User:dev@example.com:Developer access::

group:admins:admin@pve,root@pam:Full administrators:
group:operators:operator@pve:Operations team:

role:PVEAdmin:VM.Allocate,VM.Audit,VM.Backup,VM.Clone,VM.Config.CDROM,VM.Config.CPU,VM.Config.Cloudinit,VM.Config.Disk,VM.Config.HWType,VM.Config.Memory,VM.Config.Network,VM.Config.Options,VM.Console,VM.Migrate,VM.Monitor,VM.PowerMgmt,VM.Snapshot,VM.Snapshot.Rollback,Datastore.Allocate,Datastore.AllocateSpace,Datastore.AllocateTemplate,Datastore.Audit,Permissions.Modify,Pool.Allocate,Pool.Audit,SDN.Allocate,SDN.Audit,Sys.Audit,Sys.Console,Sys.Incoming,Sys.Modify,Sys.PowerMgmt,Sys.Syslog,User.Modify:

acl:1:/:root@pam:Administrator:
acl:1:/:admin@pve:Administrator:
acl:1:/:operator@pve:Administrator:
acl:1:/storage:backup@pve:PVEAdmin:
acl:1:/:dev@pve:PVEAdmin:

token:root@pam:automation:0:0:Automation scripts:
token:root@pam:monitoring:0:0:Monitoring integration:
token:admin@pve:ci-deploy:0:0:CI/CD deployment token:
`,

  'cluster.fw': `# Proxmox VE Cluster Firewall Configuration
# /etc/pve/firewall/cluster.fw
# Last modified: 2025-11-20

[OPTIONS]

enable: 0

[RULES]

`,

  'iptables': `# Generated by iptables-save on Proxmox VE 8.1
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
`,

  'lxc.conf': `# Container 100
hostname: webserver-prod
unprivileged: 0
features: nesting=1,keyctl=1
mp0: /mnt/shared,mp=/shared
mp1: /mnt/backup,mp=/backup
rootfs: local-lvm:vm-100-disk-0,size=32G
cores: 4
memory: 4096
swap: 512
net0: name=eth0,bridge=vmbr0,ip=192.0.2.10/24,gw=192.0.2.1

# Container 101
hostname: database-prod
unprivileged: 0
features: nesting=1
mp0: /mnt/data,mp=/var/lib/mysql
rootfs: local-lvm:vm-101-disk-0,size=64G
cores: 8
memory: 8192
swap: 1024
net0: name=eth0,bridge=vmbr0,ip=192.0.2.11/24,gw=192.0.2.1

# Container 102
hostname: docker-host
unprivileged: 0
features: nesting=1,keyctl=1,mount=nfs;cifs
rootfs: local-lvm:vm-102-disk-0,size=100G
cores: 8
memory: 16384
swap: 2048
net0: name=eth0,bridge=vmbr0,ip=192.0.2.12/24,gw=192.0.2.1
`,

  'storage.cfg': `dir: local
	path /var/lib/vz
	content iso,vztmpl,backup
	maxfiles 3

lvmthin: local-lvm
	thinpool data
	vgname pve
	content rootdir,images

nfs: nas-backups
	server 198.51.100.10
	export /volume1/pve-backups
	content backup,iso
	options vers=3,no_root_squash
	maxfiles 5

nfs: nas-shared
	server 198.51.100.10
	export /volume1/shared
	content images,rootdir
	options no_root_squash,rw

cifs: smb-archive
	server 198.51.100.20
	share pve-archive
	content backup
	username guest
	options file_mode=0777,dir_mode=0777,sec=none
	domain WORKGROUP
`,
};
