/**
 * Partially Hardened Sample Configuration
 * Some security measures applied, but gaps remain. Expected score: C (~65-75)
 *
 * - SSH key auth, but root login allowed (prohibit-password)
 * - Firewall enabled, but default policy ACCEPT
 * - Some users have 2FA, some don't
 * - Mix of privileged and unprivileged containers
 * - API tokens exist but with some controls
 */
import type { ConfigFileType } from '../types';

export const partialSample: Record<ConfigFileType, string> = {
  'sshd_config': `# Proxmox VE 8.2 SSH Configuration
# /etc/ssh/sshd_config
# Partially hardened — key-only for most, root via key

Port 22
ListenAddress 0.0.0.0

# Authentication — keys preferred but passwords still allowed
PermitRootLogin prohibit-password
PasswordAuthentication yes
PubkeyAuthentication yes
PermitEmptyPasswords no
MaxAuthTries 6
LoginGraceTime 60

X11Forwarding no
UsePAM yes

Subsystem sftp /usr/lib/openssh/sftp-server
`,

  'user.cfg': `# Proxmox VE User Configuration
# /etc/pve/user.cfg

user:root@pam:1:0::::Superuser::
user:admin@pve:1:0:Sarah:Chen:sarah@example.com:Primary admin::
user:operator@pve:1:0:Mike:Rodriguez:mike@example.com:Ops lead::
user:devops@pve:1:0:Alex:Kim:alex@example.com:DevOps engineer::
user:readonly@pve:1:0:Audit:User:audit@example.com:Readonly access::

group:admins:admin@pve:Administrators:
group:operators:operator@pve,devops@pve:Operations:
group:viewers:readonly@pve:Read-only:

role:PVEAdmin:VM.Allocate,VM.Audit,VM.Backup,VM.Clone,VM.Config.CDROM,VM.Config.CPU,VM.Config.Disk,VM.Config.HWType,VM.Config.Memory,VM.Config.Network,VM.Config.Options,VM.Console,VM.Migrate,VM.Monitor,VM.PowerMgmt,VM.Snapshot,VM.Snapshot.Rollback,Datastore.Allocate,Datastore.AllocateSpace,Datastore.Audit,Pool.Audit,SDN.Audit,Sys.Audit,Sys.Console,Sys.Modify,Sys.PowerMgmt,Sys.Syslog:

acl:1:/:root@pam:Administrator:
acl:1:/:admin@pve:PVEAdmin:
acl:1:/vms:operator@pve:PVEVMAdmin:
acl:1:/vms:devops@pve:PVEVMAdmin:
acl:1:/:readonly@pve:PVEAuditor:

token:admin@pve:terraform:0:1:Terraform provisioning:
token:devops@pve:ansible:0:1:Ansible automation:

tfa:admin@pve:totp:
tfa:operator@pve:totp:
`,

  'cluster.fw': `# Proxmox VE Cluster Firewall Configuration
# /etc/pve/firewall/cluster.fw
# Firewall enabled but policies need work

[OPTIONS]

enable: 1
policy_in: ACCEPT
policy_out: ACCEPT
log_level_in: info

[RULES]

IN ACCEPT -source 192.0.2.0/24 -p tcp -dport 8006 # Proxmox UI from management
IN ACCEPT -source 192.0.2.0/24 -p tcp -dport 22 # SSH from management
IN ACCEPT -p tcp -dport 3128 # SPICE proxy — too open

[IPSET management]

192.0.2.0/24
198.51.100.0/24
`,

  'iptables': `# Generated by iptables-save on Proxmox VE 8.2
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -s 192.0.2.0/24 -p tcp --dport 8006 -j ACCEPT
-A INPUT -s 192.0.2.0/24 -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 3128 -j ACCEPT
COMMIT
`,

  'lxc.conf': `# Container 200
hostname: web-frontend
unprivileged: 1
features: nesting=0
rootfs: local-lvm:vm-200-disk-0,size=16G
cores: 2
memory: 2048
swap: 256
net0: name=eth0,bridge=vmbr0,ip=192.0.2.20/24,gw=192.0.2.1

# Container 201
hostname: app-backend
unprivileged: 1
features: nesting=0
rootfs: local-lvm:vm-201-disk-0,size=32G
cores: 4
memory: 4096
swap: 512
net0: name=eth0,bridge=vmbr0,ip=192.0.2.21/24,gw=192.0.2.1

# Container 202
hostname: docker-runner
unprivileged: 0
features: nesting=1,keyctl=1
rootfs: local-lvm:vm-202-disk-0,size=50G
cores: 4
memory: 8192
swap: 1024
net0: name=eth0,bridge=vmbr0,ip=192.0.2.22/24,gw=192.0.2.1

# Container 203
hostname: legacy-app
unprivileged: 0
features: nesting=0
rootfs: local-lvm:vm-203-disk-0,size=20G
cores: 2
memory: 2048
swap: 256
net0: name=eth0,bridge=vmbr0,ip=192.0.2.23/24,gw=192.0.2.1
`,

  'storage.cfg': `dir: local
	path /var/lib/vz
	content iso,vztmpl,backup
	maxfiles 5

lvmthin: local-lvm
	thinpool data
	vgname pve
	content rootdir,images

nfs: nas-backups
	server 198.51.100.10
	export /volume1/pve-backups
	content backup
	options vers=4.1
	maxfiles 7

cifs: smb-templates
	server 198.51.100.20
	share pve-templates
	content vztmpl,iso
	username pvebackup
	options file_mode=0640,dir_mode=0750
	domain CORP
`,
};
